### ISSUE TITLE
Desktop app for  Linux

### ISSUE THREAD

**Issue by beeltetun** [tnrich/ove-electron#1]
Hi,
would it be possible to create a Desktop app for Linux? 
Thanks

**Comment by tnrich** [comment]
Yep definitely! I can work on adding that and let you know when it's
released. I don't have a Linux machine so you'll need to try it out and
make sure it works :)

**Comment by tnrich** [comment]
@beeltetun can you try out this release and let me know if it works for you?
https://github.com/tnrich/ove-electron/releases/tag/v0.1.5

**Comment by tnrich** [comment]
Also if you don't mind I'm just curious how you stumbled upon OVE @beeltetun ? 

:)

**Comment by beeltetun** [comment]
The linux version works great! I cannot see any differences to the windows version. I cam across OVE when I was looking for a alternative to ApE, which I mainly use at work.

**Comment by tnrich** [comment]
@beeltetun that's great to hear! I've registered the linux app with "snapcraft" so I believe it should auto-update when I push new releases. Would it be ok to ask you to verify that that process is working when I make the next release? 

Thanks!
