### ISSUE TITLE
save and export functions missing file extension by default

### ISSUE THREAD

**Issue by jdmccauley** [tnrich/ove-electron#10]
OVE Release 0.1.10

OS: Windows 10 Version 1909
OS2: macOS Catalina

Hi @tnrich 

I was testing OVE 0.1.10 and noticed that the 'save', 'save as' and 'export' functions do not include the desired file extension by default. When I 'save', 'save as' or 'export' a file, there is no extension included in the file by default. Because of this, when I save a file without reading, I just get a 'file'. Thankfully this 'file' can be opened in OVE and parsed back to its original format (cannot be done with 'import sequence', but that makes sense so please don't change).

Even when I choose to export as Genbank, Fasta, or json, the default extension is none so the resulting file is just a 'file'. Saving a file prompts the user to save as a new file, so the same issue is present.

Current solution is to manually add the correct extension when naming the file, but a fix for giving the correct default extension will be ideal.

Best,
Josh
![files](https://user-images.githubusercontent.com/22922096/89081904-54f68b00-d341-11ea-83f3-0b4dc47ec1ba.PNG)

**Comment by tnrich** [comment]
Hey @jdmccauley I'm looking at this now and think that this must be another Windows-specific bug because I am having trouble reproducing on my mac. Here's what the File>Save dialog looks like for me: 

![image](https://user-images.githubusercontent.com/2730609/89087089-ea951900-d347-11ea-8190-1b90e3f68763.png)


Do you also have a Mac, and if so, would you mind checkin that the default extension is being added correctly?

Thanks!

**Comment by jdmccauley** [comment]
HIi @tnrich 

I just got a mac loaned to me recently and I tried to reproduce. I found the issue on my end:

When saving a file, the name included .gb by default. I was giving the file a new name, and wasn't realizing that the .gb was getting dropped.

I'm new to mac, so is there normally a 'file format' option when saving files? There is when I save a text file, but not for the export function in OVE. In Windows, there is a dropdown for the file type when saving a file, like I see when saving a text file on the mac. This drop down only has an option for '*' meaning 'nonetype' in Windows when I save on Windows. In OVE for the mac, there is no option, just asks for file name, tags, and location. Attaching pictures for reference.

Best,
Josh
<img width="558" alt="saving_a_text_file" src="https://user-images.githubusercontent.com/22922096/89088076-604eb400-d34b-11ea-8a2d-81471a6f34e2.png">
<img width="1003" alt="saving_a_gb" src="https://user-images.githubusercontent.com/22922096/89088079-62b10e00-d34b-11ea-9329-0add5472374a.png">

**Comment by tnrich** [comment]
Hmm that is an interesting difference. Good digging! I'll need to see if Electron supports having the file type chooser in the "Save As" dialog.

**Comment by jdmccauley** [comment]
@tnrich 
Thanks! If it does, maybe that should work for both operating systems.

**Comment by jdmccauley** [comment]
@tnrich 
This looks promising
https://stackoverflow.com/questions/43136567/electron-save-dialog-specify-file-type

**Comment by tnrich** [comment]
@jdmccauley I think I've fixed this in the latest release https://github.com/tnrich/ove-electron/releases/tag/v1.1.0. Can you try that out and let me know if it fixes it for ya?

Cheers!

**Comment by jdmccauley** [comment]
Hi @tnrich,

I apologize for the late reply. The change works! On my Windows machine, if I click 'Save As' under 'File', the correct extension is added! Thank you!

The extension is not added with the 'Export Sequence' buttons under 'File', but hey, the 'Save As' is honestly more intuitive to use and I'm super happy with it!

Cheers,
Josh
