### ISSUE TITLE
Trouble loading program in windows 10

### ISSUE THREAD

**Issue by pmaye** [tnrich/ove-electron#12]
For some reason I cannot get the installation to run on my windows 10 OS.  WIndows defender initially stopped it.  So I turned that off, but it still would not run and eventually the file would disappear.  Any thoughts?

**Comment by tnrich** [comment]
Hey @pmaye I'm not sure what could be going on.. I believe that it has worked fine in the past for other Windows users. I think I'd need more info.. What do you mean that the file would "disappear"? 

Maybe another windows user can confirm that it is working for them on Windows 10?  @tiffanydai @deltuhvee 

I'll check with my company too.

**Comment by pmaye** [comment]
?That's all I can really tell you.  When I try to run the exe file, a minute or so goes by and then the file is gone.  I imagine it is probably still with the windows antivirus system.


Peter Maye, PhD | Associate Professor
Department of Reconstructive Sciences
Center for Regenerative Medicine
University of Connecticut Health Center
phone: 860-679-7347
________________________________

**Comment by tgadam** [comment]
@pmaye I just tested installing this on a Windows 10 laptop. My account was a local administrator account that did not use the Windows Live sign-in feature. After downloading the .exe and trying to run it, a Windows Defender message popped-up saying it had blocked the app. When I clicked the "Learn more" link in that message, then I was able to click "Run Anyway" and run the app.

**Comment by pmaye** [comment]
I selected run anyway and it didn’t run. Then 15-30sec later the file disappeared.  I will discuss with my IT dept.
thanks peter

Sent from my iPhone

On Oct 6, 2020, at 1:31 PM, tgadam <notifications@github.com> wrote:

﻿
*** Attention: This is an external email. Use caution responding, opening attachments or clicking on links. ***

@pmaye<https://urldefense.com/v3/__https://github.com/pmaye__;!!N0rdg9Wr!7YhA0f-Qc7ytEyXiixNvui9_OZzCUrKWthsD2CKdoYIqTNz9L1FmCgVRFOQ2dw$> I just tested installing this on a Windows 10 laptop. My account was a local administrator account that did not use the Windows Live sign-in feature. After downloading the .exe and trying to run it, a Windows Defender message popped-up saying it had blocked the app. When I clicked the "Learn more" link in that message, then I was able to click "Run Anyway" and run the app.

**Comment by tnrich** [comment]
@pmaye any luck getting it to work or still having issues?

**Comment by tnrich** [comment]
@pmaye I published a new version using electron 11. It's possible that your issue has been resolved by the updates.. Maybe worth giving it another shot :)

**Comment by tnrich** [comment]
@pmaye just published a new release https://github.com/tnrich/ove-electron/releases/tag/v1.1.0 that has an even more recent version of electron.

Maybe give that a whirl? I'm going to close this but feel free to re-open if you're still having issues.
