### ISSUE TITLE
export or print map

### ISSUE THREAD

**Issue by Benjou** [tnrich/ove-electron#15]
The print button pops up a print preview window, but the print button within this window does nothing.
An alternative would be to be able to export the map as vector graphics (svg, eps, pdf).

**Comment by tnrich** [comment]
@Benjou thanks for the issue! I can confirm that this does not work as expected. I am looking into why it isn't working now and will let you know when I push a fix.

**Comment by Benjou** [comment]
Brilliant. thanks for the  great work!

**Comment by tnrich** [comment]
@Benjou here's the new release. Let me know if it fixes the print issue you were seeing: https://github.com/tnrich/ove-electron/releases/tag/v1.0.0

**Comment by Benjou** [comment]
Hi @tnrich , Unfortunately I now have an error when I install the new version. I tried first uninstalling the previous version, but no luck...
Thanks for your reactivity!

![image](https://user-images.githubusercontent.com/9350330/105975333-c01de180-6086-11eb-9626-3b92eedd6e7d.png)

**Comment by tnrich** [comment]
@Benjou thanks for testing out the release! Sounds like there might be a bug with the most recent version of bio-parsers. I'm not sure why that module wouldn't have made it into the app..? I'll investigate and let you know. 

🙏

**Comment by tnrich** [comment]
@Benjou looks like it is related to this issue: https://github.com/electron-userland/electron-builder/issues/3185 

I'm looking into what I can do to fix it. :(

**Comment by tnrich** [comment]
@Benjou can you try out the latest release and see if it is fixed? https://github.com/tnrich/ove-electron/releases/tag/v1.0.1

**Comment by Benjou** [comment]
Works like a charm. thanks!

To keep you busy (but maybe I should open a new bug report/feature request?), the printed pdf doesn't use the same font as the software.

I am exploring the app and I am impressed! Thanks!

**Comment by tnrich** [comment]
@Benjou I don't quite have the bandwidth to solve the missing font issue with print but I encourage you to play around with the source repo https://github.com/TeselaGen/openVectorEditor to see if you can get it to work. I'd be happy to accept a PR :) 

I'm not 100% sure but I would be the code is accidentally stripping the font files from the print styles before print occurs. Probably something in this file around this line is doing it  https://github.com/TeselaGen/openVectorEditor/blob/master/src/helperComponents/PrintDialog/index.js

Cheers!
Thomas
