### ISSUE TITLE
newer linux appimage

### ISSUE THREAD

**Issue by 0xpsi** [tnrich/ove-electron#27]
On the newer builds I don't see an .appimage available, is there some docs on how I can build those myself or otherwise get the newer updates on linux?

**Comment by tnrich** [comment]
@0xpsi I must have done this on accident. I'll publish a newer version with the linux build in it shortly!

**Comment by tnrich** [comment]
@0xpsi aha! I remembered why I didn't publish the linux build. I was hitting this issue with snapcraft: https://bugs.launchpad.net/snapcraft/+bug/1925374

It looks like it's been fixed so let me try to update electron and electron builder and see if it works.

**Comment by tnrich** [comment]
Ok published https://github.com/tnrich/ove-electron/releases/tag/v1.2.4 

Lemme know if that works for you @0xpsi 

Cheers!

**Comment by 0xpsi** [comment]
> Ok published https://github.com/tnrich/ove-electron/releases/tag/v1.2.4
> 
> Lemme know if that works for you @0xpsi
> 
> Cheers!

thanks a lot! I got it and it works :D
