### ISSUE TITLE
Primers not showing on map

### ISSUE THREAD

**Issue by 0xpsi** [tnrich/ove-electron#31]
genbank files with "primer_bind" feature are recognized in ove-electron, but don't display in the plasmid map. I tried both light/dark modes. The primers DO show up on the openvectoreditor demo (http://teselagen.github.io/openVectorEditor/#/Editor) but not the standalone ove-electron (only tried on linux)

**Comment by gmcarthuriv** [comment]
@tnrich, I can confirm this. For example, the first screenshot below is a sequence displayed in TeselaGen's Design module - can clearly see the primer_bind feature annotations and labels. However, upon export and opening in ove-electron, the primer_bind feature annotations and labels are not displayed.

![image](https://user-images.githubusercontent.com/17152701/129998060-19830417-daf1-440e-8b5c-1ac214fd89be.png)

![image](https://user-images.githubusercontent.com/17152701/129998160-f141d1e1-7e6c-4507-b0d8-a0c7e961845a.png)

**Comment by tnrich** [comment]
Fixed in https://github.com/tnrich/ove-electron/releases/tag/v1.2.5
