### ISSUE TITLE
ove-electron cannot save feature notes in genbank files

### ISSUE THREAD

**Issue by jdmccauley** [tnrich/ove-electron#5]
Hello tnrich,

I am a Vector Editor user at JBEI, and I downloaded ove-electron to use it offline.

I was making edits to a sequence in ove-electron, where I wanted to make a feature and give it a feature note. I was able to do so, and export the sequence as a genbank file.

The exported genbank file did have the new features, but it lacked the feature notes. This was also true if I added a feature note to an existing feature. In all, I noticed that the current version of ove-electron cannot save feature notes when exporting as a genbank file.

If I made edits to the genbank file in a text editor and loaded the edited file into ove-electron, the feature and feature notes were able to be viewed. So ove-electron can view feature notes, it just cannot save them into genbank files.

I hope this issue request is helpful, and I can answer any more questions you have about the issue.

Best,
Joshua McCauley

**Comment by tnrich** [comment]
Hey @jdmccauley I believe this is indeed a bug. I think it is within our parsers/ove itself so I'll check it out there and confirm. Thanks for letting me know :)

**Comment by tnrich** [comment]
Can you check to see if this is working now @jdmccauley ? I think this may have been fixed in the latest release

**Comment by jdmccauley** [comment]
@tnrich 
Sorry for not responding earlier, I think I lost the notification.
I tested and it still works in this new release, just like it did in 0.1.9. Did find another issue when testing, so will report.
This issue is resolved! Thanks for the update!
