### ISSUE TITLE
OVE not opening files with 'open file'

### ISSUE THREAD

**Issue by jdmccauley** [tnrich/ove-electron#8]
@tnrich 

OVE Version: 0.1.9
OS: Windows 10 Version 1909

Hi Thomas,

I have been trying to view sequences in OVE, and I was having some issues. I was trying to run 'open file' (crtl+o) for both FASTAs and GenBank files, and OVE would close immediately when trying to open the file.

I can 'import sequence' for FASTAs and GenBank files and those parse/render fine, but 'open file' still does not. 

Is 'open file' supposed to open FASTA and GenBank files, or is that function supposed to do something else?

Best,
Josh

**Comment by jdmccauley** [comment]
Made a quick gif of the issue.
[ove_issue.zip](https://github.com/tnrich/ove-electron/files/4984989/ove_issue.zip)

**Comment by tnrich** [comment]
@jdmccauley thanks for this issue. I'll look into the .gb opening logic for windows in ove-electron. I'll let you know when I have a new version published that you can try out :)

**Comment by jdmccauley** [comment]
@tnrich Great thank you so much!

**Comment by tnrich** [comment]
@jdmccauley with the help of @deltuh-vee we got to the bottom of this windows issue. When the File>Open was being hit, we would close the old window before opening the new one. On Mac this worked fine, but on Windows closing the window would cause the whole application to close. Our fix basically loads the new window into the existing window so we don't have to worry about a "closing race condition". 

This will be released shortly.

**Comment by tnrich** [comment]
@jdmccauley here's the latest release page. Please let me know if this clears up the issue for you

https://github.com/tnrich/ove-electron/releases/tag/v0.1.10

**Comment by jdmccauley** [comment]
Hi @tnrich that sounds like a great solution! Glad I can be of help as a Windows user, and thank y'all (@deltuh-vee) for fixing this. I'll test soon!

**Comment by jdmccauley** [comment]
@tnrich @deltuh-vee
Works great, 'open' now works to open sequences without closing the application. Now I can use 'crtl + O' to open files without a pointer. Thank you for the quick solution!
